### ISSUE TITLE
Why did you use suppressHydrationWarning and react 18.3 canary?

### ISSUE THREAD

**Issue by yannickpschroeder** [kiliman/remix-vite-mui#1]
It is not really an Issue, but there are no discussions activated for this repository.
I have 2 small questions:

Why is `suppressHydrationWarning` needed at https://github.com/kiliman/remix-vite-mui/blob/main/app/root.tsx#L23?
And do we really want to use the react 18.3 canary version, or would 18.2.0 be fine as well?

Thank you for your work!

**Comment by kiliman** [comment]
Remix hydrates the whole document instead of just a root `<div>`. This causes hydration issues when you have things like browser extensions that mutate the DOM (like `<head>`) before hydration. This is a problem in React 18.2. However, they fixed this in the latest Canary version. At the time of this example, it was 18.3, but now it is v19. 

NOTE: Next.js uses React 19 Canary, and the React team says it is fully supported.

As for the `suppressHydrationWarning`, that only applies to DOM attribute mismatches. Some extraneous `data-` attributes were being added by tooling, and I wanted to ensure the DevTools console was clean. This is a personal preference. This is not the same as the hydration warnings that v19 solves.
